In [217]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.ensemble import VotingClassifier

In [218]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [220]:
df.duplicated().sum()
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [221]:
new_df  = pd.get_dummies(df, columns=['cp','sex','fbs', 'restecg','exang','slope','ca', 'thal'  ],dtype= float )

In [222]:
new_df.head()

,age,trestbps,chol,thalach,oldpeak,target,cp_0,cp_1,cp_2,cp_3,...,slope_2,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3
0,52,125,212,168,1.0,0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,53,140,203,155,3.1,0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,145,174,125,2.6,0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,61,148,203,161,0.0,0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,62,138,294,106,1.9,0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [223]:
x_new = new_df.drop('target', axis =1)
y_new = new_df['target']
x_new.shape,y_new.shape

((302, 30), (302,))

In [224]:
sc = StandardScaler()

x_new = sc.fit_transform(x_new)

In [225]:
x_new.shape

(302, 30)

In [226]:
x = df.drop('target',axis =1)
y =df['target']
x.shape,y.shape

((302, 13), (302,))

In [227]:
from sklearn.model_selection import cross_val_score
import numpy as np 

best_k = []
for value in range(1,31):
    knn = KNeighborsClassifier(n_neighbors=value)
    score = cross_val_score(knn,x_new,y_new,cv = 10, scoring='accuracy')
    best_k.append(score.mean())

best_k_arr = np.array(best_k)
print(best_k_arr.argmax()+1, best_k_arr.max())
print(best_k)
best_k_val = best_k_arr.argmax()+1

10 0.8544086021505377
[np.float64(0.7678494623655914), np.float64(0.7580645161290323), np.float64(0.7979569892473118), np.float64(0.8143010752688171), np.float64(0.8408602150537636), np.float64(0.8375268817204302), np.float64(0.8278494623655914), np.float64(0.8477419354838709), np.float64(0.8477419354838709), np.float64(0.8544086021505377), np.float64(0.8377419354838709), np.float64(0.8345161290322579), np.float64(0.8312903225806452), np.float64(0.8378494623655914), np.float64(0.8412903225806451), np.float64(0.8510752688172044), np.float64(0.8378494623655914), np.float64(0.844516129032258), np.float64(0.8410752688172044), np.float64(0.8410752688172043), np.float64(0.8377419354838709), np.float64(0.8444086021505376), np.float64(0.8410752688172043), np.float64(0.8477419354838709), np.float64(0.8509677419354839), np.float64(0.8510752688172042), np.float64(0.8477419354838709), np.float64(0.8444086021505376), np.float64(0.8444086021505376), np.float64(0.8477419354838709)]

In [228]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x_new,y, test_size =0.2,random_state = 42)

In [229]:
lor = LogisticRegression(max_iter=5000)
gnb = GaussianNB(var_smoothing=0.0001)
svc = SVC(probability=True)
knn =KNeighborsClassifier(n_neighbors=best_k_val)


estimators = [('lr',lor), ('gnb', gnb), ('svc', svc), ('knn', knn)]

In [230]:
for name,model in estimators:
    score = []
    score = cross_val_score(model, x_new,y_new,cv = 10, scoring='accuracy')
    print(name,score.mean())
    # model.fit(x_train,y_train)
    # y_pred = model.predict(x_test)
    # print(accuracy_score(y_test,y_pred), name)

lr 0.8377419354838709
gnb 0.8344086021505376
svc 0.8274193548387097
knn 0.8544086021505377

In [231]:
voting = VotingClassifier(estimators=estimators, voting='soft')
score = cross_val_score(voting,x_new,y_new,cv =10, scoring='accuracy')
print(score.mean())

0.8376344086021505

In [232]:
voting = VotingClassifier(estimators=estimators, voting='hard')
score = cross_val_score(voting,x_new,y_new,cv =10, scoring='accuracy')
print(score.mean())

0.840967741935484

In [233]:
from sklearn.feature_selection import mutual_info_classif

# A score of 0 or very close to 0. For mutual_info_classif
mi = mutual_info_classif(x,y,random_state=42)
mi_series = pd.Series(mi, index=x.columns).sort_values(ascending=False)
mi_series

thal        0.189024
cp          0.166229
ca          0.120097
exang       0.093934
chol        0.084940
oldpeak     0.084062
thalach     0.072308
slope       0.057278
trestbps    0.036479
age         0.015074
restecg     0.013636
fbs         0.007389
sex         0.007041
dtype: float64

In [234]:
# new approach 
removed_fea_df = df.drop(['restecg', 'fbs','age','trestbps'], axis=1)
removed_fea_df.head()

removed_new_df  = pd.get_dummies(removed_fea_df, columns=['cp','sex', 'exang','slope','ca', 'thal'  ],dtype= float )

In [235]:
x = removed_new_df.drop('target',axis =1)
y =removed_new_df['target']
x.shape,y.shape

((302, 23), (302,))

In [236]:
#standard scaling 
x_new = sc.fit_transform(x)

In [237]:
best_k = []
for value in range(1,31):
    knn = KNeighborsClassifier(n_neighbors=value)
    score = cross_val_score(knn,x_new,y,cv = 10, scoring='accuracy')
    best_k.append(score.mean())

best_k_arr = np.array(best_k)
print(best_k_arr.argmax()+1, best_k_arr.max())
print(best_k)
best_k_val = best_k_arr.argmax()+1

8 0.8443010752688173
[np.float64(0.7612903225806451), np.float64(0.7578494623655914), np.float64(0.8207526881720429), np.float64(0.8143010752688171), np.float64(0.8308602150537634), np.float64(0.840967741935484), np.float64(0.8440860215053764), np.float64(0.8443010752688173), np.float64(0.8378494623655914), np.float64(0.8377419354838711), np.float64(0.8211827956989246), np.float64(0.827956989247312), np.float64(0.8212903225806452), np.float64(0.8212903225806452), np.float64(0.8346236559139785), np.float64(0.8245161290322581), np.float64(0.8311827956989248), np.float64(0.8311827956989248), np.float64(0.8345161290322581), np.float64(0.8345161290322581), np.float64(0.8377419354838709), np.float64(0.8377419354838709), np.float64(0.8443010752688173), np.float64(0.8376344086021505), np.float64(0.8376344086021505), np.float64(0.8376344086021505), np.float64(0.840967741935484), np.float64(0.8376344086021505), np.float64(0.8376344086021505), np.float64(0.8343010752688172)]

In [238]:
lor = LogisticRegression(max_iter=5000)
gnb = GaussianNB(var_smoothing=0.0001)
svc = SVC(probability=True)
knn =KNeighborsClassifier(n_neighbors = best_k_val)

estimators = [('lr',lor), ('gnb', gnb), ('svc', svc), ('knn', knn)]


for name,model in estimators:
    score = []
    score = cross_val_score(model, x_new,y,cv = 10, scoring='accuracy')
    print(name,score.mean())
    # # model.fit(x_train,y_train)
    # # y_pred = model.predict(x_test)
    # print(accuracy_score(y_test,y_pred), name)

lr 0.8508602150537634
gnb 0.8278494623655914
svc 0.8244086021505377
knn 0.8443010752688173

In [239]:
voting = VotingClassifier(estimators=estimators, voting='soft')
score = cross_val_score(voting,x_new,y,cv =10, scoring='accuracy')
print(score.mean())

0.844301075268817

In [240]:
voting = VotingClassifier(estimators=estimators, voting='hard')
score = cross_val_score(voting,x_new,y,cv =10, scoring='accuracy')
print(score.mean())

0.8410752688172043