In [57]:
import pandas as pd

In [58]:
df = pd.read_csv('drug200.csv')
df.head(5)

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [59]:
df.Cholesterol.unique(), df.Drug.unique(), df.BP.unique()

(array(['HIGH', 'NORMAL'], dtype=object),
 array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object),
 array(['HIGH', 'LOW', 'NORMAL'], dtype=object))

In [60]:
x = df.drop('Drug',axis=1)
y = df.Drug

In [61]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories= [
                      ['M','F'],
                      ['HIGH','LOW','NORMAL'],
                      ['HIGH','NORMAL']                        
                    ])
x[['Sex','BP','Cholesterol']] = oe.fit_transform(x[['Sex','BP','Cholesterol']])
x.shape,y.shape

((200, 5), (200,))

In [65]:
x.head(1)

   Age  Sex   BP  Cholesterol  Na_to_K
0   23  1.0  0.0          0.0   25.355

In [67]:
dict(zip(oe.categories_[0],range(len(oe.categories_[0]))))

{'M': 0, 'F': 1}

In [66]:
dict(zip(oe.categories_[1],range(len(oe.categories_[1]))))

{'HIGH': 0, 'LOW': 1, 'NORMAL': 2}

In [68]:
dict(zip(oe.categories_[2],range(len(oe.categories_[2]))))

{'HIGH': 0, 'NORMAL': 1}

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,accuracy_score

In [63]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [64]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(DecisionTreeClassifier(), x_train,y_train,cv = 5,scoring = 'accuracy')

print(score.mean())

0.99375