In [2]:
import optuna
from sklearn.datasets import  load_breast_cancer
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import classification_report,f1_score
from sklearn.pipeline import make_pipeline

In [3]:
df  = load_breast_cancer(as_frame= True)
df = df.frame
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [4]:
df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [5]:
print(dict( df.skew() ))

{'mean radius': np.float64(0.9423795716730992), 'mean texture': np.float64(0.6504495420828159), 'mean perimeter': np.float64(0.9906504253930081), 'mean area': np.float64(1.6457321756240424), 'mean smoothness': np.float64(0.45632376481955844), 'mean compactness': np.float64(1.1901230311980404), 'mean concavity': np.float64(1.4011797389486722), 'mean concave points': np.float64(1.1711800812336282), 'mean symmetry': np.float64(0.7256089733641999), 'mean fractal dimension': np.float64(1.3044888125755076), 'radius error': np.float64(3.0886121663847574), 'texture error': np.float64(1.646443808753053), 'perimeter error': np.float64(3.443615202194899), 'area error': np.float64(5.447186284898394), 'smoothness error': np.float64(2.314450056636759), 'compactness error': np.float64(1.9022207096378565), 'concavity error': np.float64(5.110463049043661), 'concave points error': np.float64(1.4446781446974786), 'symmetry error': np.float64(2.1951328995478216), 'fractal dimension error': np.float64(3.923968620227413), 'worst radius': np.float64(1.1031152059604372), 'worst texture': np.float64(0.49832130948716474), 'worst perimeter': np.float64(1.1281638713683722), 'worst area': np.float64(1.8593732724433467), 'worst smoothness': np.float64(0.4154259962824678), 'worst compactness': np.float64(1.4735549003297956), 'worst concavity': np.float64(1.1502368219460262), 'worst concave points': np.float64(0.49261552688550875), 'worst symmetry': np.float64(1.433927765189328), 'worst fractal dimension': np.float64(1.6625792663955146), 'target': np.float64(-0.5284613207977967)}

In [6]:
x_train,x_test, y_train, y_test = train_test_split(df.drop("target", axis=1), df.target, test_size=0.2, random_state=42)

In [7]:
x_train.shape, x_test.shape

((455, 30), (114, 30))

In [8]:
sc = StandardScaler()
x_train_scaled  = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [9]:
x_test_scaled.shape

(114, 30)

In [11]:
model1 = LogisticRegression(max_iter=5000)
pipe =make_pipeline (StandardScaler(), model1)

model1.fit(x_train_scaled, y_train)
y_pred = model1.predict(x_test_scaled)

score = cross_val_score(pipe,x_train,y_train,scoring="f1",cv=3 )
print(score.mean())
print(classification_report(y_pred=y_pred,y_true= y_test))

0.9726631192761431
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [ ]:
y_pred.shape, y_test.shape

((114,), (114,))

In [ ]:
model2 = DecisionTreeClassifier(max_depth=7)
model2.fit(x_train,y_train)
y_pred = model2.predict(x_test)

score = cross_val_score(model2,x_train,y_train,scoring="f1",cv=3 )
print(score.mean())
print(classification_report(y_pred=y_pred, y_true= y_test))

0.9451727369162835
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        43
           1       0.96      0.94      0.95        71

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114

In [ ]:
model3 = SGDClassifier()
model3.fit(x_train_scaled, y_train)
y_pred = model3.predict(x_test)


score = cross_val_score(model3,x_train,y_train,scoring="f1",cv=3 )
print(score.mean())
print(classification_report(y_pred,y_test))

0.8330761865786478
              precision    recall  f1-score   support

           0       1.00      0.38      0.55       114
           1       0.00      0.00      0.00         0

    accuracy                           0.38       114
   macro avg       0.50      0.19      0.27       114
weighted avg       1.00      0.38      0.55       114

d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
df.target.value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
def objective_function(trial):
    model = trial.suggest_categorical('model_type' ,["LogisticRegression", "SDGClassifier", "DecisionTreeClassifer"])
    
    if model == "LogisticRegression":
        
        l1_ratio = trial.suggest_float('lr_l1_ratio', 0,1)
        solver  = trial.suggest_categorical('lr_solver', ["liblinear", "saga"])
        max_iter = trial.suggest_int('lr_max_iter', 200,5000)
        model = LogisticRegression(l1_ratio = l1_ratio, max_iter = max_iter)
        # model.fit(x_train_scaled,y_train)
        score = cross_val_score(model,x_train_scaled, y_train, cv = 5, scoring = "f1")
        
    elif model ==    "SDGClassifier":
        
        loss = trial.suggest_categorical('sdg_loss',["hinge", "modified_huber", "log_loss"])
        alpha = trial.suggest_float('sdg_alpha', 0.001,0.1)
        penalty = trial.suggest_categorical('sdg_penalty',["l1", "l2", "elasticnet", None])
        
        model = SGDClassifier(loss = loss, alpha = alpha, penalty = penalty)
        # model.fit(x_train_scaled, y_train)
        score = cross_val_score(model,x_train_scaled, y_train, cv = 5, scoring = "f1")
    
    else: 
        
        max_depth = trial.suggest_int('dt_max_depth',3,13)
        ccp_alpha = trial.suggest_int('dt_ccp', 0.1,1)
        model = DecisionTreeClassifier(max_depth = max_depth,ccp_alpha =  ccp_alpha, random_state = 42)  
        # model.fit(x_train,y_train)
        score = cross_val_score(model,x_train, y_train, cv = 5, scoring = "f1")
    
    return score.mean()

In [ ]:
study =optuna.create_study(direction = "maximize")
study.optimize(objective_function,n_trials = 200)

[I 2026-10-24 16:21:09,695] A new study created in memory with name: no-name-51bff581-a0e1-4496-94f5-88f44a2ef958
[I 2026-10-24 16:21:09,723] Trial 0 finished with value: 0.9777183203270161 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'log_loss', 'sdg_alpha': 0.019846677812987653, 'sdg_penalty': 'elasticnet'}. Best is trial 0 with value: 0.9777183203270161.
[I 2026-10-24 16:21:09,771] Trial 1 finished with value: 0.9303618726425666 and parameters: {'model_type': 'DecisionTreeClassifer', 'dt_max_depth': 6, 'dt_ccp': 0}. Best is trial 0 with value: 0.9777183203270161.
[I 2026-10-24 16:21:09,822] Trial 2 finished with value: 0.9366194243379024 and parameters: {'model_type': 'DecisionTreeClassifer', 'dt_max_depth': 5, 'dt_ccp': 0}. Best is trial 0 with value: 0.9777183203270161.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:09,861] Trial 3 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.10271029859565872, 'lr_max_iter': 3463}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:09,892] Trial 4 finished with value: 0.9774194684034502 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'log_loss', 'sdg_alpha': 0.014908277760606388, 'sdg_penalty': None}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:09,951] Trial 5 finished with value: 0.7719209142027934 and parameters: {'model_type': 'DecisionTreeClassifer', 'dt_max_depth': 10, 'dt_ccp': 1}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:10,028] Trial 6 finished with value: 0.7719209142027934 and parameters: {'model_type': 'DecisionTreeClassifer', 'dt_max_depth': 10, 'dt_ccp': 1}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:10,089] Trial 7 finished with value: 0.9300352447580318 and parameters: {'model_type': 'DecisionTreeClassifer', 'dt_max_depth': 10, 'dt_ccp': 0}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,127] Trial 8 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.20025677499516248, 'lr_max_iter': 1841}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:10,154] Trial 9 finished with value: 0.9718023507043471 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'modified_huber', 'sdg_alpha': 0.09777606446493553, 'sdg_penalty': None}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,196] Trial 10 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.00316504456924821, 'lr_max_iter': 4923}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,241] Trial 11 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.1514289590465392, 'lr_max_iter': 2515}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,281] Trial 12 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.5621171247102297, 'lr_max_iter': 1793}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,323] Trial 13 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.3059185471579614, 'lr_max_iter': 3106}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,366] Trial 14 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.34401203385576823, 'lr_max_iter': 334}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,419] Trial 15 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.2261545714046524, 'lr_max_iter': 4104}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,462] Trial 16 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.9326281060547137, 'lr_max_iter': 986}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,513] Trial 17 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.006821043271740851, 'lr_max_iter': 3345}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,555] Trial 18 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.47616799707330854, 'lr_max_iter': 1960}. Best is trial 3 with value: 0.9792190949059882.
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
d:\Coding\deep-learning-pytorch\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-10-24 16:21:10,599] Trial 19 finished with value: 0.9792190949059882 and parameters: {'model_type': 'LogisticRegression', 'lr_l1_ratio': 0.1498784326706843, 'lr_max_iter': 3859}. Best is trial 3 with value: 0.9792190949059882.
[I 2026-10-24 16:21:10,623] Trial 20 finished with value: 0.9827878368508054 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.08099755498163869, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,649] Trial 21 finished with value: 0.9794564516959252 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.0980388456096578, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,675] Trial 22 finished with value: 0.9794564516959252 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.09377849132151816, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,701] Trial 23 finished with value: 0.9794564516959252 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.09457809534476495, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,729] Trial 24 finished with value: 0.9810474115169135 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.07847487912198002, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,755] Trial 25 finished with value: 0.9827878368508054 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.06855726593281736, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,781] Trial 26 finished with value: 0.9679233236251836 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.06852181957055803, 'sdg_penalty': 'l1'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,807] Trial 27 finished with value: 0.9792490799134846 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.06614687259491932, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,831] Trial 28 finished with value: 0.9810187214085266 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.06767112368973711, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,855] Trial 29 finished with value: 0.9760081758338564 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.0751148898694394, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.
[I 2026-10-24 16:21:10,880] Trial 30 finished with value: 0.982605012566627 and parameters: {'model_type': 'SDGClassifier', 'sdg_loss': 'modified_huber', 'sdg_alpha': 0.049609242597244044, 'sdg_penalty': 'l2'}. Best is trial 20 with value: 0.9827878368508054.

In [ ]:
study.best_value

0.9844969822780918

In [ ]:
study.best_params

{'model_type': 'SDGClassifier',
 'sdg_loss': 'hinge',
 'sdg_alpha': 0.05955734281775242,
 'sdg_penalty': 'l2'}

In [ ]:
study.best_trial

FrozenTrial(number=88, state=<TrialState.COMPLETE: 1>, values=[0.9844969822780918], datetime_start=datetime.datetime(2026, 10, 24, 16, 21, 12, 610400), datetime_complete=datetime.datetime(2026, 10, 24, 16, 21, 12, 637180), params={'model_type': 'SDGClassifier', 'sdg_loss': 'hinge', 'sdg_alpha': 0.05955734281775242, 'sdg_penalty': 'l2'}, user_attrs={}, system_attrs={'tpe:relative_params:0': '{"model_type": "SDGClassifier"}'}, intermediate_values={}, distributions={'model_type': CategoricalDistribution(choices=('LogisticRegression', 'SDGClassifier', 'DecisionTreeClassifer')), 'sdg_loss': CategoricalDistribution(choices=('hinge', 'modified_huber', 'log_loss')), 'sdg_alpha': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'sdg_penalty': CategoricalDistribution(choices=('l1', 'l2', 'elasticnet', None))}, trial_id=88, value=None)

In [ ]:
number = 90
if number == 100 :
    print(number)
elif number == 32:
    print(number)
else:
    print(number)

90