In [1]:
import pandas as pd 
import numpy as np

In [5]:
date = pd.read_csv("orders.csv" )
time = pd.read_csv("messages.csv")

print(date.head())
print(time.head())

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3
                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

# 1. Working with date and time

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
date['date'] = pd.to_datetime(date['date'])
date.head(2)

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
## functions of after converting to datetime object the date col

date['year'] = date['date'].dt.year
date['month'] = date['date'].dt.month
date['day'] = date['date'].dt.day

date.sample(5)

          date  product_id  city_id  orders  year  month  day
811 2018-11-03        2430       23       8  2018     11    3
12  2019-03-15        5665        5       1  2019      3   15
609 2018-10-21        1933       21      19  2018     10   21
44  2018-08-03         803       23       9  2018      8    3
113 2018-12-15        6288        2       2  2018     12   15

In [ ]:
##saem goes for the time col i time df first you have to convert it to datetime object and then you can find the hour minue seconds everything abou the date 

# you can also find quater of the year by using dt.quarter and you can also find the day of the week by using dt.dayofweek and you can also find the week of the year by using dt.weekofyear and you can also find the day of the year by using dt.dayofyear and you can also find the is_month_start and is_month_end by using dt.is_month_start and dt.is_month_end and you can also find the is_quarter_start and is_quarter_end by using dt.is_quarter_start and dt.is_quarter_end and you can also find the is_year_start and is_year_end by using dt.is_year_start and dt.is_year_end