## What is a Scikit learn Pipeline?
    Pipeline chain together multiple so that  the output of each step is used as the input to the next step.

    Pipelines makes it easy to use the same preprocessing to train and test .

REFERENCE VIDEO :- http://youtube.com/watch?v=xOccYkgRV4Q

In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
df  = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

df.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
657         0       3  female  32.0      1      1  15.500        Q
23          1       1    male  28.0      0      0  35.500        S
113         0       3  female  20.0      1      0   9.825        S
884         0       3    male  25.0      0      0   7.050        S
492         0       1    male  55.0      0      0  30.500        S

In [4]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=["Survived"]),df['Survived'],test_size = 0.2,random_state=42)

In [ ]:
v