## What is a Scikit learn Pipeline?
    Pipeline chain together multiple so that  the output of each step is used as the input to the next step.

    Pipelines makes it easy to use the same preprocessing to train and test .

REFERENCE VIDEO :- http://youtube.com/watch?v=xOccYkgRV4Q

In [21]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [22]:
df  = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin','Pclass'])

df.sample(5)

     Survived     Sex   Age  SibSp  Parch      Fare Embarked
31          1  female   NaN      1      0  146.5208        C
783         0    male   NaN      1      2   23.4500        S
881         0    male  33.0      0      0    7.8958        S
70          0    male  32.0      0      0   10.5000        S
522         0    male   NaN      0      0    7.2250        C

In [24]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=["Survived"]),df['Survived'],test_size = 0.2,random_state=42)

In [25]:
df.Age.isnull().sum()

np.int64(177)

In [26]:
df.Embarked.isnull().sum()

np.int64(2)

In [27]:
trf1 = ColumnTransformer(transformers=[
    ('age_Imputer',SimpleImputer(),[2]),
    ('embarked_Imputer',SimpleImputer(strategy='most_frequent'),[6])
], remainder= 'passthrough'
                         )

In [28]:
df.Sex.isnull().sum()

np.int64(0)

In [32]:
df.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [30]:
# still it is acategorical value so we need to encode it using one hot encoding as there is no order 

trf2 = ColumnTransformer(transformers=[
    ('sex_embarked_One-hot_encoder',OneHotEncoder(sparse_output=False),[1,6])
])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

trf3 = ColumnTransformer(transformers=[
    ('scaler',MinMaxScaler(),slice(0,10))  # we have 8 columns after one hot encoding so we need to scale all the columns slice func will do that for all columns ie applying the min max sccaler 
])

In [33]:
# you could complete the  pipeline here or you could add a classifier or regressor to the pipeline and then complete it and you can also add a feature selection step in this pipeline 

# for this i will be adding the classifier to the pipeline and then complete it 

trf4 = DecisionTreeClassifier()

In [34]:
pipeline = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
])

# Pipeline Vs make_pipeline